export const GET_TASK_CONNECT = 'GET_TASK_CONNECT';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';

export const DELETE_TASK_CONNECT = 'DELETE_TASK_CONNECT';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const POST_TASK_CONNECT = 'POST_TASK_CONNECT';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE';

export const GETBYID_TASK_CONNECT = 'GETBYID_TASK_CONNECT';
export const GETBYID_TASK_SUCCESS = 'GETBYID_TASK_SUCCESS';
export const GETBYID_TASK_FAILURE = 'GETBYID_TASK_FAILURE';

export const PATCH_TASK_CONNECT = 'PATCH_TASK_CONNECT';
export const PATCH_TASK_SUCCESS = 'PATCH_TASK_SUCCESS';
export const PATCH_TASK_FAILURE = 'PATCH_TASK_FAILURE';
