export const GET_TASK_CONNECT = 'GET_TASK_CONNECT';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';

export const DELETE_TASK_CONNECT = 'DELETE_TASK_CONNECT';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';
